sonar.projectKey=stash-scout
sonar.projectName=stash-scout
sonar.host.url=https://sonar.slashdir.net
sonar.sources=frontend/src,server,shared
sonar.exclusions=**/node_modules/**,**/dist-server/**,**/data/**
